server:
  port: 8080

spring:
  application:
    name: authservice
  security:
    user:
      name: admin
#      password: my-secure-password
  data:
    redis:
      host: 192.168.1.35
      port: 31015
      connect-timeout: 60000
      password: CfAb11y5gLQ3quvc
