server:
  port: 8080

spring:
  application:
    name: authservice
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.actuate.autoconfigure.availability.AvailabilityProbesHealthEndpointGroups
  datasource:
    url: jdbc:postgresql://192.168.1.35:32172/postgres_auth
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      # password: my-secure-password

redis:
  host: 192.168.1.35
  port: 31015
  connect-timeout: 60000
  password: "CfAb11y5gLQ3quvc"

logging:
  level:
    root: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: secret_key
  expiration: 3600000

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  prometheus:
    metrics:
      export:
        enabled: true