server:
  port: 8080

spring:
  application:
    name: authservice
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.actuate.autoconfigure.availability.AvailabilityProbesHealthEndpointGroups

#  Чтобы пользователь authservice_user по умолчанию всегда попадал в нужную схему, нужно выполнить в PostgreSQL
#  ALTER ROLE authservice_user SET search_path TO authservice;
  datasource:
    url: jdbc:postgresql://192.168.1.35:32172/chatter
    username: authservice_user
    password: FufibcXDGvVgPg5qcIf8YS9z462QbIN6FbbeS3kDpbiCNBVSzioHrPm4NxpJw8G4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: authservice
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: authservice

  elasticsearch:
    uris: https://elastic.msv-tech.ru:9200
    username: elastic
    password: "5LtfVTJc002wyaI499n4oj45"

  security:
    user:
      name: admin
      # password: my-secure-password

redis:
  host: 192.168.1.35
  port: 32648
  connect-timeout: 60000
  password: "CfAb11y5gLQ3quvc"

logging:
  level:
    root: INFO
    org.springframework: DEBUG
  logstash:
    host: 192.168.1.35
    port: 30429

jwt:
  secret: secret_key
  expiration: 3600000

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true